apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformer-frontend
  namespace: platformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformer-frontend
  template:
    metadata:
      labels:
        app: platformer-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: platformer-frontend
          image: 3224142123/platformer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
