apiVersion: v1
kind: Service
metadata:
  name: platformer-frontend
  namespace: platformer
spec:
  selector:
    app: platformer-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
